on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: heavon.azurecr.io
        username: ${{ secrets.acr_heavon_username }}
        password: ${{ secrets.acr_heavon_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Shopping/Shopping.API" -f  "Shopping/Shopping.API/Dockerfile" -t heavon.azurecr.io/heavonaks:${{ github.sha }} --label dockerfile-path=Shopping/Shopping.API/Dockerfile
        docker push heavon.azurecr.io/heavonaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_heavonaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep heavon-aksbe67 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace heavon-aksbe67`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: heavon-aksbe67
        container-registry-url: heavon.azurecr.io
        container-registry-username: ${{ secrets.acr_heavon_username }}
        container-registry-password: ${{ secrets.acr_heavon_password }}
        secret-name: heavonaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: heavon-aksbe67
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          heavon.azurecr.io/heavonaks:${{ github.sha }}
        imagepullsecrets: |
          heavonaksdockerauth
